hsqldb: Add recipe
Fixes

ERROR: Nothing PROVIDES 'hsqldb' (but
meta-java/recipes-core/xml-commons/jaxme_0.5.2.bb
DEPENDS on or otherwise requires it)
ERROR: Required build target 'jaxme' has no buildable providers.
M

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Henning Heinold <heinold@inf.fu-berlin.de>